name: 'App Store Connect Application Version'
description: 'Get latest and previous versions of application from the App Store Connect'
branding:
  icon: 'smartphone'  
  color: 'blue'
inputs:
  is-itunes-lookup:
    description: 'Should action use iTunes lookup endpoint or AppStore Connect API'
    required: false
    default: 'false'
  bundle-id:
    description: 'Application bundle id (required for iTunes lookup only)'
    required: false
    default: ''
  use-https:
    description: 'Use HTTPS or HTTP (for iTunes lookup only)'
    required: false
    default: 'true'
  itunes-lookup-try-api-on-failure:
    description: 'Try to call AppStore Connect API to get application version if iTunes lookup is failed (for iTunes lookup only)'
    required: false
    default: 'true'
  app-id:
    description: 'App Store application identifier'
    required: false
    default: ''
  json-web-token:
    description: 'JSON Web Token for the App Store API request'
    required: false
    default: ''
  key-id:
    description: 'Private key ID from App Store Connect'
    required: false
    default: ''
  issuer-id:
    description: 'Issuer ID from the API Keys page in App Store Connect'
    required: false
    default: ''
  private-key-p8-path:
    description: 'Private key file downloaded from the API Keys page in App Store Connect (*.p8 file)'
    required: false
    default: ''
  private-key-p8-base64:
    description: 'Private key downloaded from the API Keys page in App Store Connect (*.p8 file) in Base64 format'
    required: false
    default: ''
  private-key-raw:
    description: 'Raw private key downloaded from the API Keys page in App Store Connect'
    required: false
    default: ''
  versions-limit:
    description: 'Number of versions to return. Maximum value is 200.'
    required: false
    default: '2'
outputs:
  app-version-latest:
    description: 'Latest app version'
  app-state-latest:
    description: 'Latest app state'
  app-release-type-latest:
    description: 'Latest app release type'
  version-created-date-latest:
    description: 'Latest app version created date'
  app-version-previous:
    description: 'Previous app version'
  app-state-previous:
    description: 'Previous app state'
  app-release-type-previous:
    description: 'Previous app release type'
  version-created-date-previous:
    description: 'Previous app version created date'
  versions-output-json:
    description: 'API response in JSON format'
runs:
  using: 'node16'
  main: './src/index.js'
